### ISSUE TITLE
 Some ticks are lagging

### ISSUE THREAD

**Issue by Fredh1000** [Wind-Development/WindSpigot#82]

**Comment by ghost** [comment]
This seems like standard server lag, caused by heavy usage or lack of hardware. For the performance part, WindSpigot is most likely lacking some optimizations either from newer Nacho versions or optimizations from Nacho that were removed due to them being unsafe and possibly causing or just causing issues.

**Comment by Fredh1000** [comment]
Even using good hardware I don't know why it rolls a tick with a duration of more than 100 ms, but the tps are stop at 20.
